name: Playwright Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Cache Playwright browsers
      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      # Install dependencies and Playwright browsers (only if not cached)
      - name: Install dependencies and Playwright browsers
        run: |
          npm ci
          npx playwright install
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      # Confirm that the Playwright browsers are installed
      - name: Verify Playwright browser installation
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run ui-tests

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: playwright-report
