name: Playwright Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure directories exist
      - name: Create necessary directories
        run: |
          mkdir -p ~/.npm
          mkdir -p .cache/playwright/chromium
          mkdir -p .cache/playwright/firefox
          mkdir -p .cache/playwright/webkit

      # Cache NPM packages
      - name: Cache NPM packages
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: |
            .cache/playwright/chromium
            .cache/playwright/firefox
            .cache/playwright/webkit
          key: playwright-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-${{ hashFiles('package.json') }}-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers only if cache is not restored
      - name: Install Playwright browsers
        run: npx playwright install
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run ui-tests
        continue-on-error: true

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
