name: Playwright Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e \"const pkgLock = require('./package-lock.json'); const version = pkgLock.devDependencies?.['@playwright/test']?.version; console.log(version || 'Not found')\")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{env.PLAYWRIGHT_VERSION}}
      - run: npm ci
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Install Playwright browsers (only if not cached)
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run ui-tests

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: playwright-report
